#! /bin/bash

dots=(
    .config
    .openvpn
    .screenlayout
    .scripts
    .bash_profile
    .bashrc
    .gitconfig
    .profile
    .tmux.conf
    .xinitrc
    .Xresources
    .zshrc
)

for d in ${dots[*]}; do
    target=$HOME/$d

    if [ ! -L "$target" ]; then
        ln -s $PWD/$d $target
        echo "symlink for $target created"
    else
        echo "symlink for $target already exists"
    fi
done

