#! /bin/sh

sxhkd &

bspc monitor -d 1 2 3 4 5 6 7 8 9 10

bspc config focused_border_color  	"#7c4d99"
bspc config normal_border_color   	"#262626"
bspc config border_width		5
bspc config window_gap			20

bspc config split_ratio			0.50
bspc config single_monocle		true
bspc config borderless_monocle		true
bspc config gapless_monocle		true
