#!/bin/bash

sxhkd &

bspc config remove_unplugged_monitors   true
bspc config remove_disabled_monitors    true

# Ensure that no `configure-monitors` processes are running
# before starting new ones
killall -q configure-monitors
while pgrep -f configure-monitors > /dev/null; do sleep 1; done

~/.scripts/configure-monitors
bspc subscribe monitor_geometry | while read -r line; do
  notify-send 'Updating monitor(s)'
  ~/.scripts/configure-monitors
done &

bspc config focused_border_color    "#a57b06"
bspc config normal_border_color     "#262626"
bspc config border_width            5
bspc config window_gap              0

bspc config split_ratio             0.50
bspc config single_monocle          true
bspc config borderless_monocle      true
bspc config gapless_monocle         true
bspc config pointer_follows_focus   true
