#!/bin/bash
# inspired by https://github.com/polybar/polybar-scripts/tree/master/polybar-scripts/system-bluetooth-bluetoothctl

output() {
    OUTPUT=""

    POWERED_ON=$(bluetoothctl show | grep "Powered: yes")
    if [ -z "$POWERED_ON" ]; then
        ICON=""
    else
        ICON=""

        PAIRED_DEVICES=$(bluetoothctl devices | grep Device | cut -d ' ' -f 2)
	CONNECTED_DEVICES=$(bluetoothctl devices Connected | cut -d ' ' -f 3)

        for d in ${CONNECTED_DEVICES=[*]}; do
            OUTPUT="$OUTPUT $d"
        done
    fi

    echo "$ICON$OUTPUT"
}

toggle_power() {
    POWERED_ON=$(bluetoothctl show | grep "Powered: yes")
    if [ -z "$POWERED_ON" ]; then
        bluetoothctl power on >> /dev/null
    else
        bluetoothctl power off >> /dev/null
    fi
}

toggle_connection() {
  DEVICE=$1

  CONNECTED=$(bluetoothctl info $DEVICE | grep "Connected: yes")
  if [ -z "$CONNECTED" ]; then
    connect $DEVICE
  else
    disconnect $DEVICE
  fi
}

connect() {
    DEVICE=$1

    bluetoothctl connect $DEVICE >> /dev/null
}

disconnect() {
    DEVICE=$1

    bluetoothctl disconnect $DEVICE >> /dev/null
}

case $1 in
    --toggle-power)
        toggle_power
        ;;
    --toggle-connection)
        toggle_connection $2
        ;;
    --connect)
        connect $2
        ;;
    --disconnect)
        disconnect $2
        ;;
    --output)
        output
        ;;
esac
