#!/bin/bash
# inspired by https://github.com/polybar/polybar-scripts/tree/master/polybar-scripts/system-bluetooth-bluetoothctl

output() {
    OUTPUT=""

    POWERED_ON=$(bluetoothctl show | grep "Powered: yes")
    if [ -z "$POWERED_ON" ]; then
        ICON=""
    else
        ICON=""

        PAIRED_DEVICES=$(bluetoothctl paired-devices | grep Device | cut -d ' ' -f 2)

        for d in ${PAIRED_DEVICES[*]}; do
            DEVICE_INFO=$(bluetoothctl info "$d")
            DEVICE_CONNECTED=$(echo $DEVICE_INFO | grep "Connected: yes")

            if [ ! -z "$DEVICE_CONNECTED" ]; then
                DEVICE_ALIAS=$(echo "$DEVICE_INFO" | grep "Alias" | cut -d ' ' -f 2-)
                OUTPUT="$OUTPUT $DEVICE_ALIAS"
            fi
        done
    fi

    echo "$ICON$OUTPUT"
}

toggle_power() {
    POWERED_ON=$(bluetoothctl show | grep "Powered: yes")
    if [ -z "$POWERED_ON" ]; then
        bluetoothctl power on >> /dev/null
    else
        bluetoothctl power off >> /dev/null
    fi
}

connect() {
    DEVICE=$1

    bluetoothctl connect $DEVICE >> /dev/null
}

case $1 in
    --toggle-power)
        toggle_power
        ;;
    --connect)
        connect $2
        ;;
    --output)
        output
        ;;
esac
