#!/bin/bash
#
# ./brightness +|- <INT>

brightness_change=$1

handler="/sys/class/backlight/intel_backlight"

max_brightness=$(cat $handler"/max_brightness")
min_brightness=0

current_brightness=$(cat $handler"/brightness")

current_brightness_p=$(( 100 * $current_brightness / $max_brightness ))
new_brightness_p=$(( $current_brightness_p + $brightness_change ))

new_brightness=$(( $max_brightness * $new_brightness_p / 100 ))

if [ $new_brightness -lt $min_brightness ]; then
    new_brightness=0
fi

if [ $new_brightness -gt $max_brightness ]; then
    new_brightness=$max_brightness
fi

echo $new_brightness > $handler"/brightness"
