#!/bin/bash

configure_monitors() {
    MAIN_MONITOR="eDP-1"
    EXTERNAL_MONITOR=$(xrandr --query | grep "HDMI-1 connected" | cut -d " " -f1)

    if [ ! -z ${EXTERNAL_MONITOR} ]; then
        ~/.screenlayout/laptop+hdmi.sh
        bspc monitor $MAIN_MONITOR -d 1 2 3 4 5
        bspc monitor $EXTERNAL_MONITOR -d 6 7 8 9 10
    else
        ~/.screenlayout/laptop.sh
        bspc monitor $MAIN_MONITOR -d 1 2 3 4 5 6 7 8 9 10
    fi

    ~/.scripts/bar &
}

configure_monitors

bspc subscribe monitor_geometry | while read -r line; do
    notify-send 'Updating monitor(s)'
    configure_monitors
done &
