#!/bin/bash
#
# Usage:
# ./mullvadvpn --toggle
# ./mullvadvpn --output

STATUS_DISCONNECTING="Disconnecting..."
STATUS_DISCONNECTED="Disconnected"
STATUS_CONNECTING="Connecting"
STATUS_CONNECTED="Connected"

status() {
  STATUS=$(mullvad status | awk '{print $3}')
  echo $STATUS
}

output() {
  CURRENT_STATUS=$(status)

  case $(status) in
    $STATUS_DISCONNECTED)
      echo "" ;;
    $STATUS_CONNECTING)
      echo " Connecting" ;;
    $STATUS_CONNECTED)
      echo "" ;;
    $STATUS_DISCONNECTING)
        echo " Disconnecting" ;;
      *)
        echo " status unknown" ;;
    esac
}


toggle() {
    CURRENT_STATUS=$(status)
    echo $CURRENT_STATUS

    case "$CURRENT_STATUS" in
      $STATUS_DISCONNECTED)
        mullvad connect ;;
      $STATUS_CONNECTED)
        mullvad disconnect ;;
    esac
}

case $1 in
    --toggle)
        toggle
        ;;
    --output)
        output
        ;;
esac
