#!/bin/bash
#
# Usage:
# ./vpn --toggle <SOME VPN CONNECTION DEFINED IN NetworkManager>
# ./vpn --status <SOME VPN CONNECTION DEFINED IN NetworkManager>

status() {
    VPN=$1

    CONNECTED=$(nmcli connection show --active | grep $VPN)

    if [ -z "$CONNECTED" ]; then
        echo ""
    else
        echo " $VPN"
    fi
}

toggle() {
    VPN=$1

    CONNECTED=$(nmcli connection show --active | grep $VPN)

    if [ -z "$CONNECTED" ]; then
        nmcli connection up $VPN
    else
        nmcli connection down $VPN
    fi
}

case $1 in
    --toggle)
        toggle $2
        ;;
    --status)
        status $2
        ;;
esac
