#!/bin/sh

CURRENT_NODE=$(bspc query -N -n)

# Enter directory to give fzf/ripgrep better context of what files are interesting
cd ~/vimwiki

# Add a one time rule (not persisted) to open any new node on the primary
# monitor in fullscreen
bspc rule --add \* --one-shot desktop=^3 follow=on

# Open vimwiki in alacritty
alacritty --command tmux new-session -A -s vimwiki 'nvim -c VimwikiIndex'

# Return to the node where this script was invoked
bspc node -f $CURRENT_NODE
